name = "lotus-testground"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
runtime_image = "iptestground/oni-runtime:596ed33"
build_base_image = "iptestground/oni-buildbase:596ed33"
enable_go_build_cache = true
skip_runtime_image = false

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "lotus-network"
instances = { min = 5, max = 5, default = 5 }

[testcases.params]
   miner-count = { type = "int", default = 2 }
