name: Comment with sorted PR checks

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull request number'
        required: true
  workflow_run:
    workflows:
      - Build
      - Check
      - CodeQL
      - Test
    types:
      - requested
      - completed

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.pull_number || github.event.workflow_run.pull_requests[0].number }}
  cancel-in-progress: true

jobs:
  comment:
    if: github.event.inputs.pull_number || github.event.workflow_run.event == 'pull_request'
    uses: ipdxco/sorted-pr-checks/.github/workflows/comment.yml@v1
    with:
      pull_number: ${{ github.event.inputs.pull_number || github.event.workflow_run.pull_requests[0].number }}
      template: unsuccessful_only
