---
name: trigger-helm-deploy
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "kubernetes namespace"
      release:
        description: "helm release"
      chart:
        description: "the helm chart"
      chart_version:
        description: "the helm chart version"
      helm_append:
        description: "append this to the end of the helm command (i.e to add more -set's)"
      override_repository:
        description: "helm chart image.repository"
      override_tag:
        description: "helm chart image.tag"
      slack_channel:
        description: "the slack channel where notifications are sent"
        default: "fil-infra-alerts"
      circle_branch:
        description: "circleci branch (used for testing new lotus-infra deploy code)"
        default: master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_TOKEN }}
          project-slug: filecoin-project/lotus-infra
          branch: ${{ github.event.inputs.circle_branch }}
          payload: |
            {
              "api_workflow_requested": "helm-deploy",
              "namespace": "${{ github.event.inputs.namespace }}",
              "release": "${{ github.event.inputs.release }}",
              "chart": "${{ github.event.inputs.chart }}",
              "chart_version": "${{ github.event.inputs.chart_version }}",
              "helm_append": "${{ github.event.inputs.helm_append }}",
              "override_repository": "${{ github.event.inputs.override_repository }}",
              "override_tag": "${{ github.event.inputs.override_tag }}",
              "slack_channel": "${{ github.event.inputs.slack_channel }}"
            }
